/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_996344_18_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_996344_4[] = { "Diseased", "Healthy", "Low_Water" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_996344_17_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
const uint32_t ei_dsp_config_996344_17_axes_size = 10;
ei_dsp_config_flatten_t ei_dsp_config_996344_17 = {
    17, // uint32_t blockId
    1, // int implementationVersion
    10, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const uint8_t ei_dsp_blocks_996344_4_size = 1;
ei_model_dsp_t ei_dsp_blocks_996344_4[ei_dsp_blocks_996344_4_size] = {
    { // DSP block 17
        17,
        70, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_996344_17, // pointer to config struct
        ei_dsp_config_996344_17_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_996344_17_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_996344_18 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_996344_18_init,
    .model_invoke = &tflite_learn_996344_18_invoke,
    .model_reset = &tflite_learn_996344_18_reset,
    .model_input = &tflite_learn_996344_18_input,
    .model_output = &tflite_learn_996344_18_output,
};

const uint8_t ei_output_tensors_indices_996344_18[1] = { 0 };
const uint8_t ei_output_tensors_size_996344_18 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_996344_18 = {
    .implementation_version = 1,
    .block_id = 18,
    .output_tensors_indices = ei_output_tensors_indices_996344_18,
    .output_tensors_size = ei_output_tensors_size_996344_18,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_996344_18,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_996344_4_size = 1;
const uint32_t ei_learning_block_996344_18_inputs[1] = { 17 };
const uint8_t ei_learning_block_996344_18_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_996344_4[ei_learning_blocks_996344_4_size] = {
    {
        18,
        &run_nn_inference,
        (void*)&ei_learning_block_config_996344_18,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_996344_18_inputs,
        ei_learning_block_996344_18_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_996344_18 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_996344_4_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_996344_4[ei_postprocessing_blocks_996344_4_size] = {
    {
        .block_id = 18,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_996344_18,
        .input_block_id = 18
    },
};

const uint8_t freeform_outputs_996344_4_size = 0;

uint32_t *freeform_outputs_996344_4 = nullptr;

const ei_impulse_t impulse_996344_4 = {
    .project_id = 996344,
    .project_owner = "zsh2451",
    .project_name = "zsh2451-project-1",
    .impulse_id = 4,
    .impulse_name = "Impulse #4",
    .deploy_version = 1,

    .nn_input_frame_size = 70,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 10,
    .dsp_input_frame_size = 1 * 10,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_996344_4_size,
    .dsp_blocks = ei_dsp_blocks_996344_4,

    .learning_blocks_size = ei_learning_blocks_996344_4_size,
    .learning_blocks = ei_learning_blocks_996344_4,

    .postprocessing_blocks_size = ei_postprocessing_blocks_996344_4_size,
    .postprocessing_blocks = ei_postprocessing_blocks_996344_4,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "F1_415nm + F2_445nm + F3_480nm + F4_515nm + F5_555nm + F6_590nm + F7_630nm + F8_680nm + NIR + Clear",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_996344_4,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_996344_4_size,
    .freeform_outputs = freeform_outputs_996344_4
};

ei_impulse_handle_t impulse_handle_996344_4 = ei_impulse_handle_t( &impulse_996344_4 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_996344_4;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_996344_4;
const auto ei_dsp_blocks_size = ei_dsp_blocks_996344_4_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_996344_4;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
