const char char_html[] = "<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Leaves Config</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#f0f4f0;color:#2d3a2d;min-height:100vh;padding:16px}"
".card{background:#fff;border-radius:12px;padding:24px;margin-bottom:16px;box-shadow:0 2px 8px rgba(0,0,0,0.08)}"
"h1{text-align:center;color:#3a7d44;font-size:24px;margin-bottom:8px}"
".subtitle{text-align:center;color:#6b8e6b;margin-bottom:24px;font-size:14px}"
"h2{font-size:16px;color:#3a7d44;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #e8f0e8}"
"label{display:block;font-size:13px;color:#555;margin-bottom:4px;font-weight:500}"
"input,select{width:100%;padding:10px 12px;border:1px solid #d0dcd0;border-radius:8px;font-size:14px;outline:none;transition:border 0.2s}"
"input:focus,select:focus{border-color:#3a7d44}"
".field{margin-bottom:14px}"
"button{width:100%;padding:12px;border:none;border-radius:8px;font-size:16px;font-weight:600;cursor:pointer;transition:all 0.2s}"
".btn-save{background:#3a7d44;color:#fff;margin-top:8px}"
".btn-save:hover{background:#2d6336}"
".btn-scan{background:#5a9e6f;color:#fff;margin-bottom:12px}"
".btn-scan:hover{background:#4a8e5f}"
".btn-reset{background:#d9534f;color:#fff;margin-top:8px}"
".btn-reset:hover{background:#c9302c}"
"#status{text-align:center;padding:12px;border-radius:8px;margin-top:12px;display:none;font-size:14px}"
".status-ok{background:#d4edda;color:#155724;display:block!important}"
".status-err{background:#f8d7da;color:#721c24;display:block!important}"
".status-loading{background:#fff3cd;color:#856404;display:block!important}"
".wifi-list{max-height:200px;overflow-y:auto;border:1px solid #d0dcd0;border-radius:8px;margin-top:8px}"
".wifi-item{padding:8px 12px;cursor:pointer;border-bottom:1px solid #e8f0e8;font-size:14px}"
".wifi-item:hover{background:#e8f0e8}"
".wifi-item:last-child{border-bottom:none}"
".checkbox-field{display:flex;align-items:center;margin-bottom:10px}"
".checkbox-field input[type=checkbox]{width:auto;margin-right:8px;transform:scale(1.3)}"
".checkbox-field label{margin-bottom:0;cursor:pointer;font-size:14px}"
".optional-section{border-left:3px solid #3a7d44;padding-left:12px;margin-top:8px}"
".disabled{opacity:0.5;pointer-events:none}"
"</style></head><body>"
"<h1>Leaves</h1>"
"<p class='subtitle'>Plant Spectral Analysis - Config Wizard</p>"
"<div class='card'>"
"<h2>WiFi Config</h2>"
"<button class='btn-scan' onclick='scanWifi()'>Scan WiFi</button>"
"<div id='wifiList' class='wifi-list' style='display:none'></div>"
"<div class='field'><label>WiFi SSID</label>"
"<input id='ssid' placeholder='WiFi name'></div>"
"<div class='field'><label>WiFi Password</label>"
"<input id='password' type='password' placeholder='WiFi password'></div>"
"<div class='field'><label>Device Name</label>"
"<input id='deviceName' placeholder='leaves_device'></div>"
"</div>"
"<div class='card'>"
"<h2>Feature Config</h2>"
"<div class='checkbox-field'>"
"<input type='checkbox' id='enableAutoNet'>"
"<label for='enableAutoNet'>Auto Connect WiFi on Boot</label>"
"</div>"
"<div class='checkbox-field'>"
"<input type='checkbox' id='enableMqtt' onchange='toggleMqttFields()'>"
"<label for='enableMqtt'>Enable MQTT / HomeAssistant</label>"
"</div>"
"<div id='mqttSection' class='optional-section disabled'>"
"<div class='field'><label>MQTT Server</label>"
"<input id='mqttServer' placeholder='192.168.1.100'></div>"
"<div class='field'><label>MQTT Port</label>"
"<input id='mqttPort' type='number' value='1883'></div>"
"<div class='field'><label>MQTT Username (optional)</label>"
"<input id='mqttUser' placeholder='username'></div>"
"<div class='field'><label>MQTT Password (optional)</label>"
"<input id='mqttPass' type='password' placeholder='password'></div>"
"</div>"
"<div class='checkbox-field'>"
"<input type='checkbox' id='enableAi' onchange='toggleAiFields()'>"
"<label for='enableAi'>Enable SiliconFlow AI</label>"
"</div>"
"<div id='aiSection' class='optional-section disabled'>"
"<div class='field'><label>SiliconFlow API Key</label>"
"<input id='sfKey' placeholder='sk-xxx...'></div>"
"<div class='field'><label>ServerChan SendKey</label>"
"<input id='scKey' placeholder='SCTxxx...'></div>"
"</div>"
"</div>"
"<button class='btn-save' onclick='saveConfig()'>Save and Connect</button>"
"<button class='btn-reset' onclick='resetConfig()'>Factory Reset</button>"
"<div id='status'></div>"
"<script>"
"function setStatus(msg,type){var s=document.getElementById('status');s.textContent=msg;s.className='status-'+type}"
"function toggleMqttFields(){var checked=document.getElementById('enableMqtt').checked;var sec=document.getElementById('mqttSection');if(checked){sec.classList.remove('disabled')}else{sec.classList.add('disabled')}}"
"function toggleAiFields(){var checked=document.getElementById('enableAi').checked;var sec=document.getElementById('aiSection');if(checked){sec.classList.remove('disabled')}else{sec.classList.add('disabled')}}"
"function scanWifi(){setStatus('Scanning...','loading');fetch('/api/scan').then(r=>r.json()).then(data=>{var list=document.getElementById('wifiList');list.innerHTML='';list.style.display='block';data.forEach(function(ap){var div=document.createElement('div');div.className='wifi-item';div.textContent=ap.ssid+' ('+ap.rssi+'dBm)';div.onclick=function(){document.getElementById('ssid').value=ap.ssid};list.appendChild(div)});setStatus('Found '+data.length+' networks','ok')}).catch(function(e){setStatus('Scan failed: '+e.message,'err')})}"
"function saveConfig(){var cfg={ssid:document.getElementById('ssid').value,password:document.getElementById('password').value,deviceName:document.getElementById('deviceName').value,enableMqtt:document.getElementById('enableMqtt').checked,enableAi:document.getElementById('enableAi').checked,enableAutoNet:document.getElementById('enableAutoNet').checked,enableAutoNet:document.getElementById('enableAutoNet').checked,mqttServer:document.getElementById('mqttServer').value,mqttPort:document.getElementById('mqttPort').value,mqttUser:document.getElementById('mqttUser').value,mqttPass:document.getElementById('mqttPass').value,sfKey:document.getElementById('sfKey').value,scKey:document.getElementById('scKey').value};if(!cfg.ssid){setStatus('WiFi SSID required','err');return}if(!cfg.password){setStatus('WiFi Password required','err');return}if(cfg.enableMqtt&&!cfg.mqttServer){setStatus('MQTT Server required when enabled','err');return}if(cfg.enableAi&&!cfg.sfKey){setStatus('API Key required when AI enabled','err');return}setStatus('Saving...','loading');fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)}).then(r=>r.json()).then(data=>{if(data.ok){setStatus('Saved! Rebooting...','ok');setTimeout(function(){setStatus('Manual reboot if needed','loading')},5000)}else{setStatus('Failed: '+data.msg,'err')}}).catch(function(e){setStatus('Error: '+e.message,'err')})}"
"function resetConfig(){if(!confirm('Factory reset?'))return;setStatus('Resetting...','loading');fetch('/api/reset',{method:'POST'}).then(r=>r.json()).then(data=>{if(data.ok){setStatus('Reset done, rebooting...','ok')}else{setStatus('Reset failed','err')}}).catch(function(e){setStatus('Error: '+e.message,'err')})}"
"fetch('/api/config').then(r=>r.json()).then(data=>{if(data.ssid)document.getElementById('ssid').value=data.ssid;if(data.sfKey)document.getElementById('sfKey').value=data.sfKey;if(data.scKey)document.getElementById('scKey').value=data.scKey;if(data.mqttServer)document.getElementById('mqttServer').value=data.mqttServer;if(data.mqttPort)document.getElementById('mqttPort').value=data.mqttPort;if(data.mqttUser)document.getElementById('mqttUser').value=data.mqttUser;if(data.mqttPass)document.getElementById('mqttPass').value=data.mqttPass;if(data.deviceName)document.getElementById('deviceName').value=data.deviceName;if(data.enableMqtt){document.getElementById('enableMqtt').checked=true;toggleMqttFields()}if(data.enableAi){document.getElementById('enableAi').checked=true;toggleAiFields()}if(data.enableAutoNet)document.getElementById('enableAutoNet').checked=true})"
"</script>"
"</body></html>";
